# Generated by Django 3.1.2 on 2022-02-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(blank=True, default='images', null=True, upload_to='images')),
                ('video', models.FileField(upload_to='video/%y')),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('primary_muscles', models.ManyToManyField(related_name='primary', to='routine.Muscle')),
                ('secondary_muscles', models.ManyToManyField(related_name='secondary', to='routine.Muscle')),
            ],
        ),
    ]
