# Generated by Django 3.1.2 on 2022-03-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20220319_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box_exercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
