# Generated by Django 3.1.2 on 2022-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_auto_20220303_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='plan',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='added', to='routine.Box_exercise'),
        ),
        migrations.AddField(
            model_name='box_exercise',
            name='day',
            field=models.ManyToManyField(blank=True, related_name='onday', to='routine.Day_week'),
        ),
    ]
