# Generated by Django 3.1.2 on 2022-03-27 00:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_auto_20220319_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, 'Enter # greater than 0'), django.core.validators.MaxValueValidator(100, 'Enter # less than 100')])),
                ('series', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, 'Enter # greater than 0'), django.core.validators.MaxValueValidator(30, 'Enter # less than 30')])),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.box_exercise')),
            ],
        ),
    ]
